# https://docs.oracle.com/javase/7/docs/api/constant-values.html

MODIFIER_PUBLIC = 1 << 0
MODIFIER_PRIVATE = 1 << 1
MODIFIER_PROTECTED = 1 << 2
MODIFIER_STATIC = 1 << 3
MODIFIER_FINAL = 1 << 4
MODIFIER_SYNCHRONIZED = 1 << 5
MODIFIER_VOLATILE = 1 << 6
MODIFIER_TRANSIENT = 1 << 7
MODIFIER_NATIVE = 1 << 8
MODIFIER_INTERFACE = 1 << 9
MODIFIER_ABSTRACT = 1 << 10
MODIFIER_STRICT = 1 << 11

JAVA_NULL = 0
